title: Erik Hallmark
email: erik@erikhallmark.com
paginate: 5
description: > # this means to ignore newlines until "baseurl:"
  This is where I talk about me and the weird stuff I do. It's worth a look.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erikhallmark.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: erikhallmarkdev
github_username: erikhallmarkdev
highlighter: rouge

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
